### ISSUE TITLE
long I/O wait for large pdfs

### ISSUE THREAD

**Issue by vitamins** [TrilbyWhite/Slider#26]
For pdfs with big filesize, you have to wait quiet long for the first slide to show up.
Looks like the whole pdf is loaded before the first slide is shown.

**Comment by TrilbyWhite** [comment]
That is correct.  This was a design choice - and not a very good one it turns out.  Version 1 was multithreaded to allow for rendering in the background - but multithreading lead to all sorts of bugs, so I got rid of it in versions 2+3.  This did lead to a delay on startup for larger pdfs though.

I'm not going to fix it in version 3 as I've completely rewritten slider with a new design from the outset where each slide is rendered on demand.  Version 4 is making good progress, you can check out the v4 branch of the git repo to preview how it will work - but keep in mind v4 is still "pre-alpha" and many bits are still expected not to work.  I anticipate v4 being in at least a functional beta state by next month.
